services:
  db:
    image: arangodb/arangodb:3.12.4.3
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=password
    networks:
      - dissertations-network
    healthcheck:
      test: ["CMD", "arangosh", "--server.endpoint", "http://127.0.0.1:8529", "--server.password", "password", "--javascript.execute-string", "require('internal').print(true)"]
      interval: 10s
      timeout: 10s
      retries: 10

  selenium-chrome:
    image: selenium/standalone-chrome:4.43.0-20260404
    container_name: selenium-chrome
    ports:
      - "127.0.0.1:4444:4444"
      - "127.0.0.1:7900:7900"
    environment:
      - SE_VNC_NO_PASSWORD=1
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_NODE_SESSION_TIMEOUT=300
    shm_size: 2gb
    networks:
      - dissertations-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/status"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
      selenium-chrome:
        condition: service_healthy
    environment:
      - SELENIUM_REMOTE_URL=http://selenium-chrome:4444
      - ARANGO_HOST=http://arangodb:8529
      - ARANGO_USER=root
      - ARANGO_PASSWORD=password
      - ARANGO_DATABASE=dissertation_db
      - PYTHONUNBUFFERED=1
      - PARSE=false
      - MAX_PAGES=3
    ports:
      - "127.0.0.1:8080:8080"
    working_dir: /app
    networks:
      - dissertations-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: frontend
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - dissertations-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  dissertations-network:
    driver: bridge
